- project:
    name: Juniper/contrail-infra-doc
    check:
      jobs:
        - build-infra-doc
        - publish-infra-doc:
            dependencies:
              - build-infra-doc
    gate:
      jobs:
        - build-infra-doc
    post-merge:
      jobs:
        - publish-infra-doc
